### ISSUE TITLE
Could you give some more details about your genetic optimization method?

### ISSUE THREAD

**Issue by FinalTheory** [bruno147/fsmdriver#10]

**Comment by bruno147** [comment]
The FSMDriver uses 17 racing parameters (4 for stuck, 7 for outOfTrack and 6 for insideTrack). The parameters are float point numbers and their binary representation was used in order to create an individual. An individual has a total of 17 parameters each of them represented by 32 bits resulting in a 544 bits string.
The GA used standard configurations from literature, the population size was arbitrarily set as 30, which leads to 616 generations for a moderate problem complexity. Selection is done through elitism by keeping the best 4 individuals from a generation unchanged, and the other 26 are generated from the best 10 individuals’ reproduction. This step is done by randomly choosing a pair from the top 10 that are cloned with a 5% chance or generate a pair of offspring with a 95% probability. These offspring are produced through crossover by partitioning the parents’ bitstrings at a random position and swapping them. Finally, mutation (a simple bit flip) is applied to every bit in every individual of these 26 with a 1% probability.

**Comment by Gastd** [comment]
More information can be seen in [our paper](http://ieeexplore.ieee.org/document/7785853/)
